services:
  postgres:
    image: postgres:16
    container_name: entretods-postgres
    environment:
      POSTGRES_USER: leotdev
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
